contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nanoporemethylation channel"
    url: https://nfcore.slack.com/channels/nanoporemethylation
    about: Discussion about the nf-core/nanoporemethylation pipeline
